apiVersion: 1

datasources:
  - uid: postgres
    name: PostgreSQL
    type: grafana-postgresql-datasource
    access: proxy
    url: db:5432
    database: case_study
    user: postgres
    isDefault: true
    editable: false
    secureJsonData:
      password: admin123
    jsonData:
      sslmode: disable
      postgresVersion: 1600
